# Generated by Django 3.2.8 on 2022-03-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='i18n',
            field=models.JSONField(default=dict),
        ),
    ]
